language: java
jdk:
    - openjdk8

cache:
    directories:
        - "$HOME/.cache"
		
jobs:
    - stage: deploy
      name: 'Deploy to the environment'
      script: 
        - mvn clean install
        - cp .travis.settings.xml $HOME/.m2/settings.xml
        - mvn deploy -Dmuledploy -Dserver=$server -Denv=$env -DappName=$appName -Dver=$ver -Dworkers=$workers -Dtype=$type
      if: branch = dev