java:
 - openjdk8

cache:
    directories:
        - $HOME/.cache
 
jobs:
  #include:
    - stage: deploy
      name: 'Deploy To Dev Environment'
      script:
       - mvn clean install
       - cp .travis.settings.xml $HOME/.m2/settings.xml
       - mvn package deploy -DmuleDeploy -Dserver=$server -Denv=$env -DappName=$appName -Dver=$ver -Dworkers=$workers -Dtype=$type
      if: branch = dev
      