java:
 - openjdk8

cache:
    directories:
        - $HOME/.cache
 
jobs:
  #include:
    - stage: deploy
      name: 'Deploy To Dev Environment'
      script:
       - mvn clean install
       - cp .travis.settings.xml $HOME/.m2/settings.xml
       - mvn deploy -DmuleDeploy -Dserver=$server -Denvironment=$environment -DappName=$appName -DmuleVersion=$muleVersion -Dworkers=$workers -DworkerType=$workerType
      if: branch = dev
